name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup UV
        uses: astral-sh/setup-uv@v7

      - name: Build
        run: uv run .scripts/build.py --artifact ha-integration-meteo-france

      - name: Release
        uses: softprops/action-gh-release@v3
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          files: dist/ha-integration-meteo-france.zip
          draft: false
          prerelease: false

